from django.urls import path, include
from . import views
urlpatterns = [
    path('',views.firstpage,name="firstpage"),
    path('first/',views.start,name='start'),
    path('first/home/',views.home,name='home'), 
    path('first/home/mentor-login/mentor-signup/mentor/',views.mentor,name='mentor'),
    path('first/home/investor-login/investor-signup/investor/',views.investor,name='investor'),
    path('first/home/mentor-login/',views.mentor_login,name='mlogin'),
    path('first/home/investor-login/',views.investor_login,name='ilogin'),
    path('first/home/mentor-login/mentor-signup/',views.mentor_signup,name='mentorsignup'),
    path('first/home/investor-login/investor-signup/',views.investor_signup,name='investorsignup'),
    path('first/home/entrepreneur-login/entrepreneur-signup/',views.entrepreneur_signup,name='entrepreneursignup'),
    path('first/home/entrepreneur-login/entrepreneur-signup/terms/',views.terms,name='terms'),
    path('first/home/mentor-login/mentor-signup/terms/',views.terms,name='terms'),
    path('first/home/investor-login/investor-signup/terms/',views.terms,name='terms'),
    path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/book-mentors/',views.bookmentors,name='bookmentorss'),
    path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/book-investors/',views.bookinvestors,name='bookinvestorss'),
    path('first/home/entrepreneur-login/book-mentors/',views.bookmentors,name='bookmentors'),
    path('first/home/entrepreneur-login/book-investors/',views.bookinvestors,name='investorbooking'),
    path('first/home/mentor-login/mentor-signup/mentor-login/',views.redirectments),
    path('first/home/investor-login/investor-signup/investor-login/',views.redirectinvests),
    path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur-login/',views.redirectents),
    path('first/home/mentor-login/mentor-signup/mentor/view-requests/',views.mentor_view_requests,name='view_requests'),
    path('first/home/mentor-login/view-requests/',views.mentor_view_requests,name='view_requests'),
    path('first/home/entrepreneur-login/',views.entrepreneur_login,name='entlogin'),
    path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/',views.entrepreneur,name='entrepreneur'),

path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/booked-calls/',views.bookedcallsforents,name='bookedcalls'),
path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/booked-investor-calls/',views.bookedinvestorcallsforents,name='bookedinvestrcalls'),
    path('first/home/entrepreneur-login/booked-calls/',views.bookedcallsforents,name='bookedcallsents'),
     path('first/home/entrepreneur-login/booked-investor-calls/',views.bookedinvestorcallsforents,name='bookedinvestorcallsents'),
    path('first/home/mentor-login/mentor-signup/mentor/booked-calls/',views.bookedcallsforments,name='bookedcallsments'),
    path('first/home/investor-login/booked-calls/',views.bookedcallsforinvests,name='bookedcallinvests'),
    path('first/home/investor-login/investor-signup/investor/booked-calls/',views.bookedcallsforinvests,name='bookedcallsinvests'),
    path('first/home/mentor-login/booked-calls/',views.bookedcallsforments,name='bookedcallments'),
    path('meeting-ents/<str:room_name>/', views.video_meeting_for_ents, name='video_meeting_for_ents'),
    path('entrepreneur-dashboard/',views.entrepreneurdashboard,name='entrepreneur_dashboard'),
    path('entrepreneur-dashboard/book-mentors/',views.redirectentrepreneurstocallbooking,name='redentstocallbooking'),
     path('entrepreneur-dashboard/book-investors/',views.redirectentrepreneurstoinvestorbookings,name='redentstoinvestorbooking'),
    path('entrepreneur-dashboard/booked-calls/',views.redirectentstoviewcalls,name='redentstocallview'),
     path('entrepreneur-dashboard/booked-investor-calls/',views.redirectentstoviewinvestorcalls,name='redentstocallview'),
    path('mentor-dashboard/',views.mentordashboard,name='mentordashboard'),
     path('investor-dashboard/',views.investordashboard,name='investordashboard'),
    path('mentor-dashboard/booked-calls/',views.redirectmentstobookedcalls,name='redirectmentstobookedcalls'),
    path('investor-dashboard/booked-calls/',views.redirectinveststobookedcalls,name='redirectinveststobookedcalls'),
    path('mentor-dashboard/view-requests/',views.redirectmentstocallrequest,name='redirectmentstocallrequest'),
    path('investor-dashboard/view-requests/',views.redirectinveststocallrequest,name='redirectinveststocallrequest'),
    path('meeting-invests/<str:room_name>/', views.video_meeting_for_invests, name='video_meeting_for_invests'),
    path('meeting-ments/<str:room_name>/', views.video_meeting_for_ments, name='video_meeting_for_ments'),
     path('meeting-ents-investors/<str:room_name>/',views.video_meeting_for_ents_investors,name='video_meeting_for_ents_with_investors'),
    path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/failure-vault/submit/', views.submit_failure, name='submit_failure'),
path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/failure-vault/',views.main,name="main"),
path('first/home/entrepreneur-login/failure-vault/',views.redirectentrepreneurstofailurevault,name="main1"),
path('entrepreneur-dashboard/failure-vault/',views.redirectentrepreneurstofailurevault,name='redentstofailurevault'),
path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/failure-vault/browse/',views.browse,name='browse'),
 path('first/home/entrepreneur-login/entrepreneur-signup/entrepreneur/failure-vault/stories/', views.failures_list, name='stories_page'),

 path('first/home/investor-login/investor-signup/investor/view-requests/',views.investor_view_requests,name='view_requests_invests'),
 path('first/home/investor-login/view-requests/',views.investor_view_requests,name='view_requests_investss'),
    path('first/home/investor-login/investor-requests/',views.investor_view_requests,name='view_requests_invest'),
    path('entrepreneur-dashboard/profile/',views.entprofile,name='entprofile'),
     path('entrepreneur-dashboard/profile/edit/',views.editentprofile,name='editentprofile'),
     path('api/fetch-article/', views.fetch_article),
     path('entrepreneur-dashboard/survery-form/',views.surveyform,name='surveyform'),
          path('entrepreneur-dashboard/survery-form/form/',views.surveyform1,name='surveyform1'),
          path('mentor-review/<str:room_name>',views.mentorrating,name='review-mentor'),
           path('no-mentor-review/<str:room_name>',views.nomentorrating,name='no-review-mentor'),
path('entrepreneur-dashboard/mentorhistory',views.callhistorywithmentors,name='callhistorywithmentors')
]
